<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <title>Optimus Summary Automation</title>
     
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) 
                         ->prependStylesheet($this->basePath('css/datetimepicker.css'))?>

    </head>
    <body class="t-home">
    <div class="container-fluid">
        <div class="row t-header">
                <header class="t-header__wrapper">
                    <div class="c-logo col-xs-3 col-sm-4 col-md-7 col-lg-8">
                        <a href="#">
                            <img src="img/logo.png" />
                        </a>
                    </div>
                   
                    <div class="c-right-menu col-xs-9 col-sm-8 col-md-5 col-lg-4 text-right">
                                <ul class="list-inline c-right-menu__link">
                                    <li>
                                        <a href="#"><span>Hello</span> Amit Gupta</a>
                                    </li>
                                    <li>
                                        <a href="#">Setting</a>
                                    </li>
                                    <li>
                                        <a href="#">Logout</a>
                                    </li>
                                </ul>

                                <p class="c-right-menu__last-login-details text-left">Last Login 31st July 2015</p>
                        </div>
                    </header>
                <nav class="navbar navbar-default col-xs-12 col-sm-12 col-md-12 c-navigation">
                
                        <div class="container-fluid">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header hidden-sm hidden-md hidden-lg">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>

                                <a class="navbar-brand" href="#">Navigation</a>
                            </div>

                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="#">Dashboard <span class="sr-only">(current)</span></a></li>
                                    <li><a href="#">User</a></li>
                                    <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Action</a></li>
                                            <li><a href="#">Another action</a></li>
                                            <li><a href="#">Something else here</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">Separated link</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">One more separated link</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">Modules</a></li>
                                    <li><a href="#">Settings</a></li>
                                </ul>

                                <form class="navbar-form navbar-left c-search-form" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                    </div>
                                    <button type="submit" class="btn btn-default glyphicon glyphicon-search c-search-btn"></button>
                                </form>

                            </div><!-- /.navbar-collapse -->
                        </div><!-- /.container-fluid -->
                </nav>
            </div> <!-- End t-header -->

            <div class="row t-main">

                <div class="t-main-wrapper">

                    <div class="col-xs-12 col-sm-12 col-md-12 c-heading">
                        <h1>Dashboard</h1>
                    </div>

                    <div class="t-main-wrapper__content">

                        <div class="col-xs-12 col-sm-3 col-md-2 c-left-sidebar">
                            <div class="c-background-lightgrey c-side-menu">
                                <h2 class="c-label-heading c-side-menu__heading">Side Menu</h2>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="#">Manage Filters</a>
                                    </li>
                                    <li>
                                        <a href="#">Manage Filters</a>
                                    </li>
                                    <li>
                                        <a href="#">Manage Filters</a>
                                    </li>
                                </ul>
                            </div>

                            <div class="c-background-lightgrey c-systerm-messages">
                                <h2 class="c-label-heading c-systerm-messages__heading">Systerm Messages</h2>
                                <div class="c-systerm-messages__content">
                                    <a href="#">Latest Message</a>
                                    <ul class="list-unstyled">
                                        <li>
                                            <a href="#">Lorium Ipsum</a>
                                        </li>
                                        <li>
                                            <a href="#">Message Title</a>
                                        </li>
                                    </ul>
                                    <form>
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="input-text" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label for="input-textarea">Content</label>
                                            <textarea class="form-control" rows="3" id="input-textarea"></textarea>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="blankRadio" id="blankRadio1" value="option1" aria-label="">
                                                To every one
                                            </label>
                                            <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">Send</button>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="c-todo-complete-tab">
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs c-todo-complete-tablist" role="tablist">
                                    <li role="presentation" class="active"><a href="#todo" aria-controls="todo" role="tab" data-toggle="tab">To Do</a></li>
                                    <li role="presentation"><a href="#completed" aria-controls="completed" role="tab" data-toggle="tab">Completed</a></li>
                                </ul>

                                <!-- Tab panes -->
                                <div class="tab-content c-tab-content">
                                    <div role="tabpanel" class="tab-pane active" id="todo">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a href="#">To do will open in Model box</a>
                                                <span>Deadline: Today</span>
                                            </li>
                                            <li>
                                                <a href="#">To do will open in Model box</a>
                                                <span>Deadline: Today</span>
                                            </li>
                                            <li>
                                                <a href="#">To do will open in Model box</a>
                                                <span>Deadline: Today</span>
                                            </li>
                                        </ul>

                                        <div class="c-todo-button">
                                            <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">View All</button>
                                            <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">To Do Config</button>
                                        </div>
                                    </div>

                                    <div role="tabpanel" class="tab-pane" id="completed">
                                        <ul class="list-unstyled">
                                            <li>
                                                <a href="#">To do will open in Model box</a>
                                                <span>Deadline: Today</span>
                                            </li>
                                            <li>
                                                <a href="#">To do will open in Model box</a>
                                                <span>Deadline: Today</span>
                                            </li>
                                            <li>
                                                <a href="#">To do will open in Model box</a>
                                                <span>Deadline: Today</span>
                                            </li>
                                        </ul>

                                        <div class="c-todo-button">
                                            <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">View All</button>
                                            <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">To Do Config</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php echo $this->content; ?>
                 <!-- Open panel for right sidebar -->
                    <a id="right-sidebar-panel-link" href="#right-sidebar-panel">
                        Right Sidebar Panel
                    </a>
                    <!-- Open panel for right sidebar -->

                    <div id="right-sidebar-panel" class="col-xs-12 col-sm-3 col-md-3 c-right-sidebar">
                        <div class="c-background-lightgrey c-date-calender">
                            <h2 class="c-label-heading c-date-calender__heading">Date Calender</h2>

                            <div class="col-xs-12 col-sm-12 col-md-12 c-date-calender__date-time">
                                <span class="col-sm-6 col-md-6 time">22:15</span>
                                <span class="col-sm-6 col-md-6 date">
                                    07th Aug 2015
                                    <span>
                                        friday
                                    </span>
                                </span>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 c-date-calender__picker">

                                <div class="c-date-calender__title">
                                    <span></span>
                                    <span>
                                        Calender
                                    </span>
                                </div>

                                <div class="c-date-calender__list" style="overflow:hidden;">

                                    <div class="form-group">

                                        <div class="row">
                                            <div class="col-xs-12 col-sm-12 col-md-12">
                                                <div id="datetimepicker12"></div>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>
                        </div>

                        <div class="c-background-lightgrey c-quick-visula-linkes">
                            <h2 class="c-label-heading c-quick-visula-linkes__heading">Quick Visula Linkes</h2>
                        </div>
                    </div>

                </div>
            </div> <!-- End t-main-wrapper -->
            </div>

        </div>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/panelslider.js'))
            ->prependFile($this->basePath('js/datetimepicker.js'))
            ->prependFile($this->basePath('js/moment.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>

        <script type="text/javascript">
        $(function () {
            $('#datetimepicker12').datetimepicker({
                inline: true,
                sideBySide: true
            });

            $('#datetimepicker2').datetimepicker();
        });
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
        $('.datepicker').removeClass('col-md-6');
        $('.datepicker').addClass('col-md-12');

        $('#right-sidebar-panel-link').panelslider({
                side: 'right',
                clickClose: false,
                duration: 200
        });

        $('#right-sidebar-panel-link').on('click', function() {
            $(this).toggleClass('active-right-panel');
            if ($('.active-right-panel').length) {
                $('<div class="overlay" />').insertBefore($(this));
            } else {
                $('.overlay').remove();
            }
        });
    });
    </script>
       
    </body>
</html>
